#!/usr/bin/env bash
# Helper script to run eslint --fix + prettier, create a branch and open a PR (requires GH CLI and git creds)
# Usage: ./scripts/ci-autofix-and-pr.sh "fix-lint-<date>" "Autofix lint and format"

set -euo pipefail

BRANCH_NAME=${1:-fix/lint-autofix-$(date +%Y%m%d-%H%M%S)}
COMMIT_MSG=${2:-"chore: lint autofix"}

echo "Running eslint --fix..."
npx eslint --fix "src/**/*.{ts,tsx,js,jsx}" || true

echo "Running prettier..."
npx prettier --write "src/**/*.{ts,tsx,js,jsx,json,css,md}" || true

# Show git status
if [ -n "$(git status --porcelain)" ]; then
  echo "Creating branch $BRANCH_NAME"
  git checkout -b "$BRANCH_NAME"
  git add -A
  git commit -m "$COMMIT_MSG"
  echo "Pushing branch"
  git push -u origin "$BRANCH_NAME"

  # Try to open a PR using gh (GitHub CLI) if available
  if command -v gh >/dev/null 2>&1; then
    gh pr create --fill --title "$COMMIT_MSG" --body "Autogenerated lint & format fixes. Please review." || true
  else
    echo "gh CLI not found; please create a PR for branch $BRANCH_NAME manually."
  fi
else
  echo "No changes after auto-fix. Nothing to commit."
fi

